# from typing import Tuple

# import numpy as np

# class CSR:
#     shape: Tuple[int, int]

#     def __getitem__(self, key: Tuple[int, int]) -> float: ...
#     def sort_indices(self) -> None: ...
#     def todense(self) -> np.ndarray: ...

# def cholesky(A: CSR) -> CSR: ...
# def solve_cholesky(A: CSR, b: np.ndarray) -> np.ndarray: ...
