from typing import Tuple


class CSR:
    shape: Tuple[int, int]

    def __getitem__(self, key: Tuple[int, int]) -> float: ...


class lil_array:
    shape: Tuple[int, int]

    def __init__(self, nrows: int, ncols: int) -> None: ...
    def __getitem__(self, key: Tuple[int, int]) -> float: ...
    def __setitem__(self, key: Tuple[int, int], value: float) -> None: ...
    def tocsr(self) -> CSR: ...
